total_request_timeout_secs = 30
sigul_request_timeout_secs = 5

[sigul]
bridge_hostname = "localhost"
bridge_port = 44334
server_hostname = "localhost"
sigul_user_name = "sigul-client"
private_key = "sigul.client.private_key.pem"
client_certificate = "sigul.client.certificate.pem"
ca_certificate = "sigul.ca_certificate.pem"

[[keys]]
pesign_token_name = "OpenSC Card"
pesign_certificate_name = "whatever pesign asked for"
key_name = "Sigul HSM Key"
certificate_name = "Secure Boot Code Signing Certificate"
passphrase_path = "sigul.signing-key-passphrase"

[[keys]]
pesign_token_name = "OpenSC Card"
pesign_certificate_name = "whatever pesign asked for"
key_name = "bad key"
certificate_name = "bad cert"
passphrase_path = "sigul.signing-key-passphrase"
