[alias]
xtask = "run --package xtask --"

[target.'cfg(all())']
rustflags = [
    # Reject unsafe code - we shouldn't need it for anything here.
    "-Dunsafe-code",

    # Opt in to a few additional lints from rustc
    #
    # Refer to `rustc -W help` output for lint groups and individual rules.
    "-Wfuture-incompatible",
    "-Wnonstandard-style",
    "-Wrust-2018-idioms",

    # Enable all default lint categories (correctness, suspicious, style, complexity, and perf).
    # All remaining enabled lints are from non-default categories which may, in the future, enter
    # one of the default categories.
    "-Wclippy::all",

    # Opt in to some non-standard clippy lints.
    #
    # This list was based off of the Embark Studios standard lints v6 for Rust 1.55+, but
    # has been adjusted since some lints have either been removed or moved to a default
    # category as of Rust 1.88.

    #######################################################################
    #                           Pedantic Lints                            #
    # These lints are rather strict or occasionally have false positives. #
    #######################################################################
    # The following rules are machine-applicable.
    "-Wclippy::checked_conversions",
    # This mangles the CLI documentation, it would be nice to have
    # if that quirk could be addressed.
    # "-Wclippy::doc_markdown",
    "-Wclippy::enum_glob_use",
    "-Wclippy::explicit_deref_methods",
    "-Wclippy::explicit_into_iter_loop",
    "-Wclippy::filter_map_next",
    "-Wclippy::flat_map_option",
    "-Wclippy::implicit_clone",
    "-Wclippy::inefficient_to_string",
    "-Wclippy::map_unwrap_or",
    "-Wclippy::needless_for_each",
    "-Wclippy::ptr_as_ptr",
    "-Wclippy::semicolon_if_nothing_returned",
    "-Wclippy::single_match_else",
    "-Wclippy::unnested_or_patterns",

    # The following rules are NOT machine-applicable.
    "-Wclippy::empty_enum",
    "-Wclippy::expl_impl_clone_on_copy",
    "-Wclippy::fn_params_excessive_bools",
    "-Wclippy::from_iter_instead_of_collect",
    "-Wclippy::invalid_upcast_comparisons",
    "-Wclippy::large_digit_groups",
    "-Wclippy::large_stack_arrays",
    "-Wclippy::large_types_passed_by_value",
    "-Wclippy::linkedlist",
    "-Wclippy::macro_use_imports",
    "-Wclippy::match_same_arms",
    "-Wclippy::match_wild_err_arm",
    "-Wclippy::match_wildcard_for_single_variants",
    "-Wclippy::mut_mut",
    "-Wclippy::needless_continue",
    "-Wclippy::option_option",
    "-Wclippy::ref_option_ref",
    "-Wclippy::same_functions_in_if_condition",
    "-Wclippy::string_add_assign",
    "-Wclippy::unused_self",
    "-Wclippy::zero_sized_map_values",

    #######################################################################
    #                          Restriction Lints                          #
    # These lints prevent use of various language and library features.   #
    #######################################################################
    # The following rules are machine-applicable.
    "-Wclippy::dbg_macro",
    "-Wclippy::lossy_float_literal",
    "-Wclippy::string_to_string",

    # The following rules are NOT machine-applicable.
    "-Wclippy::exit",
    "-Wclippy::float_cmp_const",
    "-Wclippy::mem_forget",
    "-Wclippy::mutex_integer",
    "-Wclippy::rc_mutex",
    "-Wclippy::rest_pat_in_fully_bound_structs",
    "-Wclippy::string_add",
    "-Wclippy::todo",
    "-Wclippy::unimplemented",
    "-Wclippy::verbose_file_reads",
    "-Wclippy::exhaustive_enums",
    "-Wclippy::indexing_slicing",

    #######################################################################
    #                            Nursery Lints                            #
    # These lints are still under development in Clippy.                  #
    #######################################################################
    # The following rules are machine-applicable.
    "-Wclippy::imprecise_flops",
    "-Wclippy::string_lit_as_bytes",
    "-Wclippy::trait_duplication_in_bounds",

    # The following rules are NOT machine-applicable.
    "-Wclippy::debug_assert_with_mut_call",
    "-Wclippy::fallible_impl_from",
    "-Wclippy::path_buf_push_overwrite",
]
