name: Github Actions lint
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/
  schedule:
    - cron: "15 0 * * SUN"

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        id: rust-toolchain
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{steps.rust-toolchain.outputs.cachekey}}

      - name: Install zizmor
        run: |
          cargo install zizmor

      - name: zizmor - GitHub actions audit
        run: zizmor --format sarif . > results.sarif
        env:
          GH_TOKEN: $${{ secrets.GITHUB_TOKEN }}

      - name: Report zizmor results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: zizmor

      - name: Check zizmor results
        run: |
          problems=$(zizmor -q --format json . | jq 'length')
          if (( $problems > 0 )); then
            echo "Found problem(s) with zizmor:"
            zizmor --format plain .
            exit 1
          fi
