name: Cargo dependency checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "45 0 * * SUN"

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
        id: rust-toolchain
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{steps.rust-toolchain.outputs.cachekey}}

      - name: Install cargo-deny
        run: |
          cargo install --locked cargo-deny

      - name: Check for security advisories
        run: cargo deny --log-level info --workspace check --show-stats advisories

      - name: Check for unexpected licenses from dependencies
        run: cargo deny --log-level info --workspace check --show-stats licenses

      - name: Check crates are from expected sources
        run: cargo deny --log-level info --workspace check --show-stats sources
